#!/bin/bash -l

#SBATCH --job-name=caffeine
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=16
#SBATCH --time=0-0:30:00
#SBATCH --account=nn4654k
#SBATCH --qos=devel

module load foss/2020a
module load Python/3.8.2-GCCcore-9.3.0

PATH=$PATH:/cluster/home/stig/src/mrchem/install-1.0.0/bin/

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
mrchem --launcher="mpirun -map-by ppr:1:numa -bind-to numa" caffeine-bp86-mw5

exit 0
